services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000" # Change to 80:3000 for deployment outside localhost
    working_dir: /frontend
    command: npm start

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5328:5328"
    environment:
      FLASK_APP: /backend/app.py
      PYTHONPATH: /
    command: python3 /backend/app.py
